package skills

import (
	"fmt"
	"strings"

	"github.com/TryCadence/Cadence/internal/ai/prompts"
)

func init() {
	Register(&CommitReview{})
}

// CommitReviewInput holds the input parameters for the commit_review skill.
type CommitReviewInput struct {
	CommitHash    string   // Full or short commit hash
	Author        string   // Commit author
	Message       string   // Commit message
	Additions     string   // Added lines (diff)
	Deletions     string   // Removed lines (diff)
	FilesChanged  []string // List of changed file paths
	AdditionCount int      // Number of lines added
	DeletionCount int      // Number of lines removed
}

// CommitReview reviews a full git commit for patterns indicating AI generation.
// Unlike CodeAnalysis (which focuses on a code snippet), this skill considers
// the commit holistically: message, author patterns, diff shape, file scope, etc.
type CommitReview struct{}

func (s *CommitReview) Name() string { return "commit_review" }
func (s *CommitReview) Description() string {
	return "Review a full git commit for AI-generation indicators"
}
func (s *CommitReview) Category() string { return "detection" }
func (s *CommitReview) MaxTokens() int   { return 1024 }

const commitReviewSystemPrompt = `You are an expert at reviewing git commits to determine whether they were authored by a human or generated by AI.

Analyze the commit holistically — consider not just the code, but also:

**Commit Message Patterns:**
- Generic messages like "Add feature", "Update file", "Fix bug"
- Overly detailed descriptions that read like documentation
- Messages that follow a rigid template without personality

**Diff Shape:**
- Unusually large additions with few or no deletions
- Perfect, uniform formatting across all changes
- Boilerplate-heavy changes with little domain-specific logic

**File Scope:**
- Many unrelated files changed at once
- Scaffold or template-like file creation patterns
- Changes that look like project initialization from a generator

**Code Quality Signals:**
- Code that is correct but lacks nuance or edge-case handling
- Overly consistent style that's "too clean" for a human session
- Generic variable names and excessive inline comments

Respond in JSON format:
{
  "assessment": "likely AI-generated|possibly AI-generated|unlikely AI-generated",
  "confidence": 0.0-1.0,
  "reasoning": "brief explanation",
  "indicators": ["indicator1", "indicator2"],
  "commit_message_score": 0.0-1.0,
  "code_score": 0.0-1.0
}`

func (s *CommitReview) SystemPrompt() string {
	return commitReviewSystemPrompt
}

func (s *CommitReview) FormatInput(input interface{}) (string, error) {
	v, ok := input.(CommitReviewInput)
	if !ok {
		return "", fmt.Errorf("commit_review: expected CommitReviewInput, got %T", input)
	}

	var b strings.Builder
	b.WriteString(fmt.Sprintf("Commit: %s\n", v.CommitHash))
	if v.Author != "" {
		b.WriteString(fmt.Sprintf("Author: %s\n", v.Author))
	}
	if v.Message != "" {
		b.WriteString(fmt.Sprintf("Message: %s\n", v.Message))
	}
	b.WriteString(fmt.Sprintf("Stats: +%d -%d across %d files\n", v.AdditionCount, v.DeletionCount, len(v.FilesChanged)))

	if len(v.FilesChanged) > 0 {
		b.WriteString("\nFiles changed:\n")
		limit := len(v.FilesChanged)
		if limit > 20 {
			limit = 20
		}
		for _, f := range v.FilesChanged[:limit] {
			b.WriteString("  " + f + "\n")
		}
		if len(v.FilesChanged) > 20 {
			b.WriteString(fmt.Sprintf("  ... and %d more\n", len(v.FilesChanged)-20))
		}
	}

	if v.Additions != "" {
		code := v.Additions
		if len(code) > 2000 {
			code = code[:2000] + "...[truncated]"
		}
		b.WriteString("\nAdditions:\n" + code + "\n")
	}

	b.WriteString("\nProvide your assessment in the JSON format specified.")
	return b.String(), nil
}

func (s *CommitReview) ParseOutput(raw string) (interface{}, error) {
	return prompts.ParseAnalysisResult(raw)
}
