codecov:
  require_ci_to_pass: yes
  max_report_age: 24

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        target: 30%
        threshold: 1%
    patch:
      default:
        target: 30%
        threshold: 0%

ignore:
  - "**/*_test.go"
  - "test/**"
  - "scripts/**"
  - "bin/**"

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: false

flags:
  unittests:
    carryforward: true
  integration:
    carryforward: false
