package main

import (
	"context"
	"fmt"
	"os"
	"time"

	"github.com/spf13/cobra"

	"github.com/codemeapixel/cadence/internal/ai"
	"github.com/codemeapixel/cadence/internal/config"
	"github.com/codemeapixel/cadence/internal/detector/patterns"
	"github.com/codemeapixel/cadence/internal/web"
)

var (
	webURL string
)

var webCmd = &cobra.Command{
	Use:   "web <url>",
	Short: "Analyze a website for AI-generated content",
	Long: `Analyze website content to detect AI-generated text ("slop").

Examines content for common AI patterns including:
- Overused phrases and generic language
- Excessive structure and formatting
- Suspiciously perfect grammar
- Boilerplate text patterns
- Lack of nuance and specific details

Returns confidence score and detailed pattern analysis.`,
	Args: cobra.ExactArgs(1),
	RunE: runWebAnalyze,
}

func init() {
	webCmd.Flags().StringVarP(&webURL, "url", "u", "", "website URL to analyze")
}

func runWebAnalyze(cmd *cobra.Command, args []string) error {
	url := args[0]

	fmt.Fprintf(os.Stderr, "Fetching website content from %s...\n", url)

	// Fetch website
	fetcher := web.NewFetcher(10 * time.Second)
	pageContent, err := fetcher.Fetch(url)
	if err != nil {
		return fmt.Errorf("failed to fetch website: %w", err)
	}

	fmt.Fprintf(os.Stderr, "Analyzing content for AI patterns...\n")

	// Analyze for text slop
	analyzer := patterns.NewTextSlopAnalyzer()
	result, err := analyzer.AnalyzeContent(pageContent.GetMainContent())
	if err != nil {
		return fmt.Errorf("analysis failed: %w", err)
	}

	// Perform AI analysis if enabled
	var aiAnalysis string
	cfgPath := configFile
	if cfgPath == "" {
		if _, err := os.Stat("cadence.yml"); err == nil {
			cfgPath = "cadence.yml"
		}
	}

	cfg, err := config.Load(cfgPath)
	if err == nil && cfg.AI.Enabled {
		fmt.Fprintf(os.Stderr, "Performing AI analysis...\n")
		aiAnalysis, err = performWebAIAnalysis(pageContent, result, &cfg.AI)
		if err != nil {
			fmt.Fprintf(os.Stderr, "Warning: AI analysis failed: %v\n", err)
		}
	}

	// Format and output results
	output := formatWebAnalysisResults(pageContent, result, aiAnalysis)
	fmt.Println(output)

	return nil
}

func performWebAIAnalysis(content *web.PageContent, result *patterns.TextSlopResult, aiCfg *config.AIConfig) (string, error) {
	ctx, cancel := context.WithTimeout(context.Background(), 2*time.Minute)
	defer cancel()

	analyzer, err := ai.NewOpenAIAnalyzer(aiCfg.APIKey, aiCfg.Model)
	if err != nil {
		return "", err
	}

	// Create analysis prompt for web content
	prompt := fmt.Sprintf(`Analyze the following website content for signs of AI generation. Consider the overall writing style, patterns, and content quality.

Website URL: %s
Title: %s
Content Summary: %d words

Content excerpt:
%s

Detected patterns: %d (confidence: %d%%)
- %v

Provide a brief assessment (2-3 sentences) of whether this content appears to be AI-generated.`,
		content.URL,
		content.Title,
		len(content.GetMainContent()),
		truncateText(content.GetMainContent(), 1000),
		len(result.Patterns),
		result.GetConfidenceScore(),
		result.Patterns,
	)

	// Use the OpenAI analyzer (reusing existing functionality)
	analysis, err := analyzer.AnalyzeWithSystemPrompt(ctx,
		"You are an expert at detecting AI-generated text and content. Analyze the provided website content and assess the likelihood it was generated by AI.",
		prompt,
	)
	if err != nil {
		return "", err
	}

	return analysis, nil
}

func formatWebAnalysisResults(content *web.PageContent, result *patterns.TextSlopResult, aiAnalysis string) string {
	output := `
╔════════════════════════════════════════════════════════════╗
║           WEBSITE AI CONTENT ANALYSIS REPORT              ║
╚════════════════════════════════════════════════════════════╝

URL: ` + content.URL + `
Title: ` + content.Title + `
Status Code: ` + fmt.Sprintf("%d", content.StatusCode) + `
Analyzed At: ` + content.FetchedAt.Format("2006-01-02 15:04:05") + `
Content Size: ` + fmt.Sprintf("%d characters", len(content.GetMainContent())) + `

ANALYSIS RESULTS
────────────────────────────────────────────────────────────
AI-Generated Content Confidence: ` + fmt.Sprintf("%d%%", result.GetConfidenceScore()) + `
Pattern Count: ` + fmt.Sprintf("%d detected", len(result.Patterns))

	if len(result.Patterns) > 0 {
		output += `

DETECTED PATTERNS
────────────────────────────────────────────────────────────`
		for i, p := range result.Patterns {
			output += fmt.Sprintf(`
%d. %s
   Severity: %.0f%%
   %s`, i+1, p.Type, p.Severity*100, p.Description)
		}
	}

	output += `

ASSESSMENT SUMMARY
────────────────────────────────────────────────────────────
` + result.GetSummary()

	if aiAnalysis != "" {
		output += `

AI EXPERT ANALYSIS
────────────────────────────────────────────────────────────
` + aiAnalysis
	}

	output += `
════════════════════════════════════════════════════════════
`

	return output
}

func truncateText(text string, maxChars int) string {
	if len(text) <= maxChars {
		return text
	}
	return text[:maxChars] + "..."
}
